name: Deploy

on:
  push:
    branches: [master]

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install node
        run: npm ci
      - name: deploy
        run: npm run deploy


